wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.8.16
    is_jupyter_run: false
    python_version: 3.7.3

Traceback (most recent call last):
  File "/ssd2/arthur/searchx-scaffolding/src/generate_relevants.py", line 35, in <module>
    generate_dataset()
  File "/ssd2/arthur/searchx-scaffolding/src/generate_relevants.py", line 22, in generate_dataset
    all_topics_path = os.path.join(config.data_home, "topics/testtest-topics_flat.txt")
  File "/home/arthur/miniconda3/envs/bert/lib/python3.7/site-packages/wandb/wandb_config.py", line 212, in __getattr__
    return self.__getitem__(key)
  File "/home/arthur/miniconda3/envs/bert/lib/python3.7/site-packages/wandb/wandb_config.py", line 202, in __getitem__
    return self._items[key]
KeyError: 'data_home'
